apiVersion: v1
kind: Service
metadata:
  name: iss-pas-service
  labels:
    app: iss-pas
    version: v1
spec:
  type: NodePort
  ports:
    - targetPort: https
      nodePort: 30123
      port: 8811
      protocol: TCP
  selector:
    app: iss-pas
    version: v1